-- Configuración de Supabase para Joa Baby Shop

-- 1. Tabla de Pedidos (Asegurar que order_number sea autoincremental)
-- ALTER TABLE orders ALTER COLUMN order_number ADD GENERATED BY DEFAULT AS IDENTITY;

-- 2. Políticas de Seguridad (RLS) para la tabla 'orders'
-- Esto es crítico para que el Checkout funcione correctamente.
ALTER TABLE orders ENABLE ROW LEVEL SECURITY;

-- Permitir que cualquier usuario (anon) inserte pedidos
CREATE POLICY "Permitir inserción pública de pedidos" 
ON orders FOR INSERT 
TO anon 
WITH CHECK (true);

-- Permitir que usuarios anónimos lean pedidos (necesario para confirmar orden_number en el frontend)
-- NOTA: En producción, podrías querer restringir esto más por privacidad.
CREATE POLICY "Permitir lectura pública de pedidos" 
ON orders FOR SELECT 
TO anon 
USING (true);

-- 3. Políticas para la tabla 'customers'
ALTER TABLE customers ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Permitir inserción/búsqueda de clientes" 
ON customers FOR INSERT 
TO anon 
WITH CHECK (true);

CREATE POLICY "Permitir lectura de clientes" 
ON customers FOR SELECT 
TO anon 
USING (true);

CREATE POLICY "Permitir actualización de clientes" 
ON customers FOR UPDATE 
TO anon 
USING (true);

-- 4. Políticas para la tabla 'products' (Permitir actualizar stock desde el checkout)
ALTER TABLE products ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Permitir lectura de productos" 
ON products FOR SELECT 
TO anon 
USING (true);

CREATE POLICY "Permitir actualización de stock" 
ON products FOR UPDATE 
TO anon 
USING (true);

-- 5. Otras tablas (Lectura pública necesaria para el Storefront)
ALTER TABLE category ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Lectura pública de categorías" ON category FOR SELECT TO anon USING (true);

ALTER TABLE delivery_methods ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Lectura pública de envíos" ON delivery_methods FOR SELECT TO anon USING (true);

ALTER TABLE payment_methods ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Lectura pública de pagos" ON payment_methods FOR SELECT TO anon USING (true);

ALTER TABLE coupons ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Lectura pública de cupones" ON coupons FOR SELECT TO anon USING (true);

ALTER TABLE store_info ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Lectura pública de info tienda" ON store_info FOR SELECT TO anon USING (true);
