-- Configuración de Supabase para Joa Baby Shop

-- 1. Tabla de Pedidos (Asegurar que order_number sea autoincremental)
-- ALTER TABLE orders ALTER COLUMN order_number ADD GENERATED BY DEFAULT AS IDENTITY;

-- 2. Políticas de Seguridad (RLS) para la tabla 'orders'
-- Esto es crítico para que el Checkout funcione correctamente.
ALTER TABLE orders ENABLE ROW LEVEL SECURITY;

-- Borrar políticas existentes si es necesario para evitar errores de duplicidad
DROP POLICY IF EXISTS "Permitir inserción pública de pedidos" ON orders;
DROP POLICY IF EXISTS "Permitir lectura pública de pedidos" ON orders;

CREATE POLICY "Permitir inserción pública de pedidos" 
ON orders FOR INSERT 
TO anon 
WITH CHECK (true);

CREATE POLICY "Permitir lectura pública de pedidos" 
ON orders FOR SELECT 
TO anon 
USING (true);

-- 3. Políticas para la tabla 'customers'
ALTER TABLE customers ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Permitir inserción/búsqueda de clientes" ON customers;
DROP POLICY IF EXISTS "Permitir lectura de clientes" ON customers;
DROP POLICY IF EXISTS "Permitir actualización de clientes" ON customers;

CREATE POLICY "Permitir inserción/búsqueda de clientes" 
ON customers FOR INSERT 
TO anon 
WITH CHECK (true);

CREATE POLICY "Permitir lectura de clientes" 
ON customers FOR SELECT 
TO anon 
USING (true);

CREATE POLICY "Permitir actualización de clientes" 
ON customers FOR UPDATE 
TO anon 
USING (true);

-- 4. Políticas para la tabla 'products' (Permitir actualizar stock desde el checkout)
ALTER TABLE products ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Permitir lectura de productos" ON products;
DROP POLICY IF EXISTS "Permitir actualización de stock" ON products;

CREATE POLICY "Permitir lectura de productos" 
ON products FOR SELECT 
TO anon 
USING (true);

CREATE POLICY "Permitir actualización de stock" 
ON products FOR UPDATE 
TO anon 
USING (true);

-- 5. Otras tablas (Lectura pública necesaria para el Storefront)
-- CORRECCIÓN: 'categories' en lugar de 'category'
ALTER TABLE categories ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Lectura pública de categorías" ON categories;
CREATE POLICY "Lectura pública de categorías" ON categories FOR SELECT TO anon USING (true);

ALTER TABLE delivery_methods ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Lectura pública de envíos" ON delivery_methods;
CREATE POLICY "Lectura pública de envíos" ON delivery_methods FOR SELECT TO anon USING (true);

ALTER TABLE payment_methods ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Lectura pública de pagos" ON payment_methods;
CREATE POLICY "Lectura pública de pagos" ON payment_methods FOR SELECT TO anon USING (true);

ALTER TABLE coupons ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Lectura pública de cupones" ON coupons;
CREATE POLICY "Lectura pública de cupones" ON coupons FOR SELECT TO anon USING (true);

ALTER TABLE store_info ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Lectura pública de info tienda" ON store_info;
CREATE POLICY "Lectura pública de info tienda" ON store_info FOR SELECT TO anon USING (true);
