-- ==========================================
-- 1. CREACIÓN DE TABLAS (SI NO EXISTEN)
-- ==========================================

-- Categorías
CREATE TABLE IF NOT EXISTS categories (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    description TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Productos
CREATE TABLE IF NOT EXISTS products (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    sku TEXT UNIQUE NOT NULL,
    name TEXT NOT NULL,
    brand TEXT,
    description TEXT,
    "ageRange" TEXT,
    "categoryId" UUID REFERENCES categories(id),
    "costPrice" NUMERIC DEFAULT 0,
    "sellingPrice" NUMERIC DEFAULT 0,
    "discountPrice" NUMERIC,
    stock INTEGER DEFAULT 0,
    "minStock" INTEGER DEFAULT 0,
    "imageUrl" TEXT,
    images JSONB DEFAULT '[]'::jsonb,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Clientes
CREATE TABLE IF NOT EXISTS customers (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL,
    phone TEXT,
    address TEXT,
    "totalOrders" INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Métodos de Envío
CREATE TABLE IF NOT EXISTS delivery_methods (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    cost NUMERIC DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Formas de Pago
CREATE TABLE IF NOT EXISTS payment_methods (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Cupones
CREATE TABLE IF NOT EXISTS coupons (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    code TEXT UNIQUE NOT NULL,
    "discountType" TEXT,
    "discountValue" NUMERIC,
    "isActive" BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Estados de Pedido
CREATE TABLE IF NOT EXISTS order_statuses (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    color TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Pedidos
CREATE TABLE IF NOT EXISTS orders (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    order_number BIGINT GENERATED BY DEFAULT AS IDENTITY,
    order_id_custom TEXT,
    "customerName" TEXT,
    "customerEmail" TEXT,
    "customerPhone" TEXT,
    "customerAddress" TEXT,
    department TEXT,
    municipality TEXT,
    "paymentMethod" TEXT,
    "deliveryMethodId" UUID,
    "deliveryMethodName" TEXT,
    items JSONB DEFAULT '[]'::jsonb,
    subtotal NUMERIC,
    coupon JSONB,
    "discountAmount" NUMERIC,
    "deliveryCost" NUMERIC,
    total NUMERIC,
    status TEXT DEFAULT 'Pendiente',
    date TIMESTAMPTZ DEFAULT NOW(),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Información de la Tienda
CREATE TABLE IF NOT EXISTS store_info (
    id INTEGER PRIMARY KEY DEFAULT 1,
    name TEXT,
    phone TEXT,
    "welcomeMessage" TEXT,
    hero_image_url TEXT,
    footer_description TEXT,
    facebook_url TEXT,
    instagram_url TEXT,
    store_address TEXT,
    store_email TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT store_info_single_row CHECK (id = 1)
);

-- ==========================================
-- 2. SEGURIDAD (RLS) Y POLÍTICAS
-- ==========================================

-- Habilitar RLS en todas las tablas
ALTER TABLE categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE products ENABLE ROW LEVEL SECURITY;
ALTER TABLE customers ENABLE ROW LEVEL SECURITY;
ALTER TABLE orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE delivery_methods ENABLE ROW LEVEL SECURITY;
ALTER TABLE payment_methods ENABLE ROW LEVEL SECURITY;
ALTER TABLE coupons ENABLE ROW LEVEL SECURITY;
ALTER TABLE store_info ENABLE ROW LEVEL SECURITY;
ALTER TABLE order_statuses ENABLE ROW LEVEL SECURITY;

-- --- POLÍTICAS PÚBLICAS (Lectura/Inserción Limitada) ---

-- Pedidos: Público solo inserta
DROP POLICY IF EXISTS "Permitir inserción pública de pedidos" ON orders;
CREATE POLICY "Permitir inserción pública de pedidos" ON orders FOR INSERT TO anon WITH CHECK (true);

-- Clientes: Público solo inserta (durante checkout)
DROP POLICY IF EXISTS "Permitir inserción de clientes" ON customers;
CREATE POLICY "Permitir inserción de clientes" ON customers FOR INSERT TO anon WITH CHECK (true);

-- Lectura Pública (Catálogo y Configuración)
DROP POLICY IF EXISTS "Lectura pública de categorías" ON categories;
CREATE POLICY "Lectura pública de categorías" ON categories FOR SELECT TO anon USING (true);

DROP POLICY IF EXISTS "Lectura pública de productos" ON products;
CREATE POLICY "Lectura pública de productos" ON products FOR SELECT TO anon USING (true);

DROP POLICY IF EXISTS "Lectura pública de envíos" ON delivery_methods;
CREATE POLICY "Lectura pública de envíos" ON delivery_methods FOR SELECT TO anon USING (true);

DROP POLICY IF EXISTS "Lectura pública de pagos" ON payment_methods;
CREATE POLICY "Lectura pública de pagos" ON payment_methods FOR SELECT TO anon USING (true);

DROP POLICY IF EXISTS "Lectura pública de cupones" ON coupons;
CREATE POLICY "Lectura pública de cupones" ON coupons FOR SELECT TO anon USING (true);

DROP POLICY IF EXISTS "Lectura pública de info tienda" ON store_info;
CREATE POLICY "Lectura pública de info tienda" ON store_info FOR SELECT TO anon USING (true);

DROP POLICY IF EXISTS "Lectura pública de estados" ON order_statuses;
CREATE POLICY "Lectura pública de estados" ON order_statuses FOR SELECT TO anon USING (true);


-- --- POLÍTICAS ADMINISTRATIVAS (Acceso Total para Autenticados) ---

DROP POLICY IF EXISTS "Gestión administrativa de categorías" ON categories;
CREATE POLICY "Gestión administrativa de categorías" ON categories FOR ALL TO authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Gestión administrativa de productos" ON products;
CREATE POLICY "Gestión administrativa de productos" ON products FOR ALL TO authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Gestión administrativa de clientes" ON customers;
CREATE POLICY "Gestión administrativa de clientes" ON customers FOR ALL TO authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Gestión administrativa de pedidos" ON orders;
CREATE POLICY "Gestión administrativa de pedidos" ON orders FOR ALL TO authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Gestión administrativa de envíos" ON delivery_methods;
CREATE POLICY "Gestión administrativa de envíos" ON delivery_methods FOR ALL TO authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Gestión administrativa de pagos" ON payment_methods;
CREATE POLICY "Gestión administrativa de pagos" ON payment_methods FOR ALL TO authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Gestión administrativa de cupones" ON coupons;
CREATE POLICY "Gestión administrativa de cupones" ON coupons FOR ALL TO authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Gestión administrativa de info tienda" ON store_info;
CREATE POLICY "Gestión administrativa de info tienda" ON store_info FOR ALL TO authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Gestión administrativa de estados" ON order_statuses;
CREATE POLICY "Gestión administrativa de estados" ON order_statuses FOR ALL TO authenticated USING (true) WITH CHECK (true);
